import { CONFIG } from "./config";
import {
  baseElevation,
  cityness,
  mountainness,
  swayScale,
  terracing,
} from "./journey";
import { underpassDepthAt } from "./junction";
import { mountainMass, ravineDepth } from "./roadFeatures";

/**
 * Road geometry math.
 * ===================
 *
 * The road is an infinitely long analytic curve rather than a set of baked
 * pieces. Everything — chunk meshes, prop placement, city layout, terrain
 * height, the car's ground height — derives from these pure functions, so
 * there is a single source of truth for "where is the road".
 *
 * Parameterisation
 * ----------------
 * `s` is distance travelled along the road, measured so that the world
 * position of the centreline is roughly (centerX(s), elevation(s), -s).
 *
 * `u` is the signed lateral offset from the centreline in metres, positive
 * to the driver's right (+X when heading straight down -Z).
 *
 * The shape of the road is not fixed: it is scaled along the route by the
 * signals in journey.ts, so the same functions produce hill switchbacks,
 * a near-straight tunnel bore and calm city streets.
 */

/** Convert a world z coordinate to the road parameter s. */
export const sFromZ = (z: number) => -z;

/** Lateral position of the centreline at distance s. */
export function centerX(s: number): number {
  let x = 0;
  for (const w of CONFIG.curve.sway) {
    x += w.amp * Math.sin((s / w.wave) * Math.PI * 2 + w.phase);
  }
  const ms = CONFIG.curve.mountainSway;
  x += mountainness(s) * ms.amp * Math.sin((s / ms.wave) * Math.PI * 2 + ms.phase);
  return x * swayScale(s);
}

/**
 * d(centerX)/ds — the road's lateral slope, used for headings and normals.
 *
 * Computed numerically. The analytic form would have to differentiate the
 * route signals as well as the sines, and any mismatch between the curve
 * and its derivative shows up as road edges that drift away from the
 * centreline. Two extra evaluations is a cheap price for that never
 * being possible.
 */
export function centerDX(s: number): number {
  const h = 0.5;
  return (centerX(s + h) - centerX(s - h)) / (2 * h);
}

/** Height of the road surface at distance s. */
export function elevation(s: number): number {
  const undulation =
    mountainness(s) *
    (3.4 * Math.sin(s * 0.0242 + 0.6) + 1.3 * Math.sin(s * 0.0561 + 3.3));
  return baseElevation(s) + undulation;
}

/**
 * Heading of the road as a yaw angle matching the vehicle convention
 * (yaw = 0 faces -Z, positive yaw turns left).
 */
export function roadYaw(s: number): number {
  return -Math.atan(centerDX(s));
}

/**
 * World-space point on the road surface at lateral offset `u`, distance `s`.
 * A true offset curve: the lateral step is taken along the curve normal, so
 * lane edges stay a constant distance from the centreline through bends.
 */
export function roadPoint(u: number, s: number, out = { x: 0, y: 0, z: 0 }) {
  const dx = centerDX(s);
  const len = Math.hypot(dx, 1);
  out.x = centerX(s) + u / len;
  out.y = elevation(s);
  out.z = -s + (u * dx) / len;
  return out;
}

/**
 * Approximate inverse of `roadPoint`: how far off the centreline is a world
 * position? Exact for points generated by roadPoint, and accurate enough
 * elsewhere given the road's curvature.
 */
export function lateralOffset(x: number, z: number): number {
  const s = sFromZ(z);
  const dx = centerDX(s);
  return (x - centerX(s)) * Math.hypot(dx, 1);
}

/** Layered pseudo-noise for gentle relief close to the road. */
function hills(x: number, z: number): number {
  return (
    3.1 * Math.sin(x * 0.021 + z * 0.017) +
    1.9 * Math.sin(x * 0.037 - z * 0.029 + 2.3) +
    0.9 * Math.sin(x * 0.081 + z * 0.063 + 5.1)
  );
}

/** Large-scale relief — the ridges and side valleys of the mid-hills. */
function ridges(x: number, z: number): number {
  return (
    26 * Math.sin(x * 0.0055 + z * 0.004) +
    15 * Math.sin(x * 0.0031 - z * 0.0071 + 1.9) +
    7 * Math.sin(x * 0.012 + z * 0.009 + 3.4)
  );
}

const smoothstep = (t: number) => {
  const c = t < 0 ? 0 : t > 1 ? 1 : t;
  return c * c * (3 - 2 * c);
};

/**
 * Ground height at any world position.
 *
 * Layered, in order:
 *  - the road surface, which the verge matches exactly
 *  - gentle relief, fading in past `flatMargin`
 *  - ridges, held back much further so the corridor and its sightlines
 *    stay open through the hills
 *  - agricultural terracing, which quantises the hillsides into steps
 *  - a hillside around the tunnel portals
 *  - the gorge under a bridge, applied everywhere including the corridor,
 *    since the whole ground must drop away beneath the deck
 *  - the Ring Road cut at Kalanki, for the same reason: the highway keeps
 *    its own surface and the ground beneath it becomes an underpass
 */
export function groundY(x: number, z: number): number {
  const s = sFromZ(z);
  const t = CONFIG.terrain;

  const u = Math.abs((x - centerX(s)) * Math.hypot(centerDX(s), 1));
  const nearFade = smoothstep((u - t.flatMargin) / t.blendDistance);
  const farFade = smoothstep((u - t.ridgeMargin) / t.ridgeBlend);

  const mountains = mountainness(s);
  const urban = cityness(s);

  // City ground is a flat valley floor; hills keep their relief.
  //
  // Dead flat in the city, again on purpose: the street grid puts roads
  // hundreds of metres off the highway, and they all have to meet at the
  // same level. Any residual relief and a side street a block away is a
  // hillside the car climbs for no reason.
  const relief = hills(x, z) * nearFade * t.amplitude * (1 - urban);
  let y =
    elevation(s) +
    relief +
    ridges(x, z) * farFade * mountains +
    mountainMass(s) * farFade;

  // Terraces: quantise the hillside into steps, blended in so the verge
  // stays smooth and the city stays flat.
  const terrace = terracing(s) * farFade * t.terraceStrength;
  if (terrace > 0.01) {
    const step = t.terraceStep;
    const stepped = Math.floor(y / step) * step + step * 0.2;
    y = y * (1 - terrace) + stepped * terrace;
  }

  return y - ravineDepth(s) - underpassDepthAt(u, s);
}

/** True when a lateral offset is on the paved surface. */
export const isOnAsphalt = (u: number) => Math.abs(u) <= CONFIG.road.laneWidth;

/**
 * Height of whatever the car is actually driving on.
 *
 * Not the same as `groundY`, and the difference matters on a bridge: there
 * the ground is the gorge floor tens of metres below, while the surface
 * under the wheels is the deck. Anything carrying the car — its position,
 * the slope it pitches to — must use this, not the terrain.
 */
export function surfaceY(x: number, z: number): number {
  const s = sFromZ(z);
  const edge = CONFIG.road.laneWidth + CONFIG.road.shoulderWidth;
  const u = Math.abs((x - centerX(s)) * Math.hypot(centerDX(s), 1));

  const road = elevation(s);
  if (u <= edge) return road;

  const t = smoothstep((u - edge) / 3);
  return road * (1 - t) + groundY(x, z) * t;
}
